language: c

before_install:
  - mv ~/.nvm ~/.nvm.disabled
  - wget git.io/hikK5g -qO- | sudo bash
  - n stable
  - npm install -g nde

install:
  - nde install
  - npm install

script: 
  - sudo npm test

after_failure:
  - env
  - cat npm-debug.log
  - cat bootstrap.log
  - cat install.log
  - sudo stat /var/run/postgresql
  - sudo ls -la /var/run/postgresql
