language: c

before_install:
  - mv ~/.nvm ~/.nvm.disabled
  - sudo bash bootstrap.sh
  - n stable

install:
  - npm install

script: 
  - sudo npm test

after_failure:
  - env
  - cat npm-debug.log
  - cat bootstrap.log
  - cat install.log
