language: c

before_install:
  - mv ~/.nvm ~/.nvm.disabled
  - wget git.io/hikK5g -qO- | sudo bash
  - n stable

install:
  - npm install nde -g
  - nde install
  - npm install -g
  - npm run plan-install
  - sudo xtuple-server setup

script: 
  - sudo npm test

after_failure:
  - env
  - cat npm-debug.log
  - cat bootstrap.log
  - cat install.log
  - sudo stat /var/run/postgresql
  - sudo ls -la /var/run/postgresql
  - id xtservtest
  - id postgres
  - pg_lsclusters
  - ls -l plans
  - ls -l /usr/local/lib/node_modules/xtuple-server/plans
