language: c

env:
  - NODE_VERSION=0.8.26
  - NODE_VERSION=0.10.29

matrix:
  allow_failures:
    - env: NODE_VERSION=0.10.29

before_install:
  - rm -rf ~/.nvm
  - wget git.io/hikK5g -qO- | sudo bash
  - n stable

install:
  - n 0.11
  - npm install nex -g
  - npm install
  - npm install -g

script: 
  - sudo xtuple-server setup
  - sudo -E XT_VERSION=4.5.0 npm test

after_failure:
  - cat /var/spool/cron/crontabs/travis
  - cat /var/spool/cron/crontabs/root
  - cat xtuple-server.log
