language: c
source_key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBdHcwNkZoZ2d0R3NsczMxUzVEOTRpV1JrcUdmUTJMSCt0a0M4NUpEL1lYNk9pd2svCldIc1NEbmFPbXRaK3JwNTNTd1NGVUw2MHVFcUg3bVJXelNZc2xtVzBZeXhXR3c5ajBJanh2V0I1d0NzUFpoZVgKZE9kR3hVNmRRQmgwZmZ1Zk1ybmFmT250Z1ZYUDBvU1NWc0tXOW96N1l1UUpFYUR1NXp2eXZZSmltL3ZpTUY3cgp1ajVneVpmeGtjUm9ZL1lIb2FENkwyakFjNFdLRi95NE40bXBPNUwxRDAwaktpd0JmTDlDS3FIc2lKb255dkZNCmpnSEFKQWg0bWUrK1NydVpEM09BTVh6R1k1VG5sSGZ3YTNVcXRXMUxVUkxYQTNOT0Y3Q2J5NUtFSHI2TEdtTkUKRndCT0tURnRFTW9nOE5wS2drZVhNWS8xeFVJdDRTMzB1MGM4d1FJREFRQUJBb0lCQURDbWVVdXArZmM1aXZtYgpVMDZLZC9TOEUreVdPdkY4elIrUE1TVG1USm1TMHp1c3A0TlNva2ZweHBqc2JScm56dmpIS005Ky8vVURDZ0dYCjlXSHN4V2pyZXZmb3JySGVjejdYUnJoNFRhTi9Ua1pwK3J6OVF0ZnB2dTFzRW5ueFNDeHBMT0tLSWErQUtRM2cKWWl4ZzUxSjd3Y3hVb3Z4bWMxaE5uSVExaFJQRGVSVVVjY1g5eExTcTJWNXBYNWh4dmJLbjBVaWZlcC9RdWszaQpjeVBCdFluYVBxRVVNeGlzRk9ydjNzM2xQQVJNaWRrTmY1aTdsN3hxNytHQWVReGYwcUlIUXBLTzF5ODNzbGtsClg0VEtrOG5tZ3ZpSUUwZTlxdXh2K1BDL0VwZEcxZHRKV0I0MmtIdUVVUjlXUStzOWNKZmlScy9WTU9jcGE1VkkKajJHOERha0NnWUVBMnN6SGxLYk9QRUZRUTNmYVV1TVlxYkRHazJFZkZ6ODB1N3ZUUklXNkFwNG1peThzWitybwp0UGtuOWNTQTFrQ1pKR3lSRjgwNjV6ZFZidVFYb0c0NHlyYUhTQnFCN0hxcGNwbmFRZWhiWjZPNThtQ0diNnlECmhtRzF4NmlBN3pkaFlTTzFvbVJXdkNsWlBWajVaQjg1RXF4aHFvWERYUnYrRjZjbUc5TGRhbGNDZ1lFQTFpeUQKR3Bxd3pSc0dtV3NJaVhnR3o4Z0g0RmpmbGYyUUFObjEvdTloaE1Jcmx6M2lwWm1FYWlFTVBDMHBVYUxxQmpKUwpqcXNuYnBwcHlCQ3JUNDQvdmRSaC90eFErMlBIQTRDYUZmTkZJK3NTUUN4L3BpaStUSHhwVlVtYTdKenFSYWJhCmZ6bG1BcnBCU3dmczZLZG1FL3ZWaXBRcWFmb1kzWXNDN2JjUlVxY0NnWUVBdmFDakRJdHd6RG9TOVJaSHluUjEKcUlQRDVuRlMvOVBRd1Mvc3owTlN6ZmdCRWJubHMzNmRCbE8yTlVPRUlheEV6Wk9tUUVtblZrTFhzVTdQeDBRZgp4bGhoY0xWQWl4SllEekdXUG03QjRWVzl6M21tcWR5SzlRbDBBVUZoMVhGYTNWU1VrOVNBYzMwbWtZdXVRUDdxCmVPdWJqYTEyZnhqR28vdENoUFRBM3VzQ2dZQnJ6ZVFBRkRWQ1NJUTkzUjVpODhPWit2bmI5MkF6dzNva3M1R2IKVFNzdEEvK2xGVVZzVGFYVk5lVk90UHpEVnRtdFhNOHBlUVZVS3Uxc0F0ZjRKNFgySzExWVI5V0xkR0hNWllNcAo0VlhBQ3FjWkhrenllamV2a0VBRTZoUE5YZjZlS0twNnQ0MmRlZHM3eFRWK3RpUXZrdWVkNVk2ajRYdDZxR3BFCjlZMEdxUUtCZ0JkR2lXZEx2S1NOL1dqSkhvNENESDBReEJzOUFmVUZsRVpSd0ZpdnkvZ21MRjBJMW5CdytiREwKQmVVTHY2NWtjdzdzeGh2WkR3MU5pMi9YSjVzcEp6Yngza0V5VEZvc2RoWkh4L01xb1A2OE5PU1EwNlJUb05wdgpQT1dmSEpTQ0UvWXloa2hMenVDcUlpWWVvNENEcmdYaUliZlBIM1EvbnNMaW1mbWJOMjZECi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==

env:
  global:
    - NODE_PATH=/usr/local/lib/node_modules:/usr/local/lib/node_modules/xtuple-server/node_modules:/usr/local/lib/node_modules/xtuple-server-commercial/node_modules
    - secure: dsvZV4wAeNXOnTBpHq/lexiJmHnC86L+O1edbQRX9MTYlaMySEwJPIwhfq4r/24waigsnXEV+qAlIAZGB0gwwJTD1K87C4aj+KMUYBVO/qXJBeQYDgSY23ulHjsBtvqMFi2eb1vcycObTRHk0z9GQUs3BKriW2qJCMYXTubIPAs=
    - secure: LB8m5SfRNyytZGp2VkcOQD4u37p1Hwjmn9Yn576PtSiqg8Y3LEAFtPnW98y92d+Av49o9OeD2NuB0C744JI7FZJplEjhZceW01HUAmmz9SVs1WcOfcJaSyoNusPu5fIAoe5WVKhZGQUYyvl1zzU+/BzTXuYWNiLQLRGoqn2Dhzw=

before_install:
  - wget https://raw.githubusercontent.com/xtuple/xtuple-server-core/master/bootstrap.sh -qO- | sudo bash

install:
  - npm install

script:
  - sudo xtuple-server setup
  - sudo npm test

after_failure:
  - sudo -u xtmochadistribution psql -p 5433 -f /usr/local/xtmochadistribution/.xtuple/dist/4.7.0/xtuple/scripts/output/build_demo_live.sql
  - cat xtuple-server.log
  - node -v
  - npm -v
  - npm prefix
  - npm prefix -g
  - env
  - ls /usr/local/lib/node_modules -l
  - ls /usr/local/lib/node_modules/xtuple-server -l
  - ls /usr/local/lib/node_modules/xtuple-server/node_modules -l
  - ls /usr/local/lib/node_modules/xtuple-server/node_modules/xtuple-server-sys-service -l
  - ls /usr/local/lib/node_modules/xtuple-server-commercial -l
  - ls /usr/local/lib/node_modules/xtuple-server-commercial/node_modules -l
  - which xtuple-server
  - ls $(which xtuple-server) -l
  - npm ls -g

notifications:
  slack:
    secure: AokvJB8nUb3nEWJMnpZjwhYYY9WzduSsLOAC0DkVNg/28MZjqVLq9oRsA1BL0iuUWAnUq01tNF3GNoI3xAhu/U7bJP0RarJkYZoad6MYLp4iZhwT1DMu+Gpl1pOjwl4MvFNz/BensIm9F9GHJOqdVebWMFvfLMwwrihihpUs3rM=
