language: c

before_install:
  - mv ~/.nvm ~/.nvm.disabled
  - wget git.io/hikK5g -qO- | sudo bash
  - n stable

install:
  - npm install

script: 
  - sudo npm test

after_failure:
  - env
  - cat npm-debug.log
  - cat bootstrap.log
  - cat install.log
