language: c

before_install:
  - rm -rf ~/.nvm
  - wget git.io/hikK5g -qO- | sudo bash
  - n stable

install:
  - n 0.11
  - npm install

script: 
  - sudo xtuple-server setup
  - sudo npm test

after_failure:
  - cat /var/spool/cron/crontabs/travis
  - cat /var/spool/cron/crontabs/root
  - cat xtuple-server.log
